headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
functionsDirectory = "/home/manumendes199514/hello-camera/ai-trainer/netlify/functions"
functionsDirectoryOrigin = "config-v1"

[functions]

[functions."*"]
node_bundler = "esbuild"

[build]
publish = "/home/manumendes199514/hello-camera/ai-trainer"
publishOrigin = "config"
commandOrigin = "ui"
command = "npm run build"
functions = "/home/manumendes199514/hello-camera/ai-trainer/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; style-src 'self' 'unsafe-inline'; script-src 'self' https://cdn.jsdelivr.net; connect-src 'self'; frame-ancestors 'self';"
Permissions-Policy = "camera=*, microphone=*, geolocation=*"
Referrer-Policy = "strict-origin-when-cross-origin"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]